### ISSUE TITLE
Target champions only

### ISSUE THREAD

**Issue by diego0700** [Wellbek/WellOrbwalker#2]
Is possible to target champion only ? It's attacking everything

**Comment by Wellbek** [comment]
It uses attack move to kite. As you may know, attack move does not only target champions. 

I advise enabling "Attack move on cursor" in the GAME options tab in League of Legends in-game settings.
![image](https://user-images.githubusercontent.com/54329793/233325102-640e4c0c-f847-4fea-999d-2ab4067e441c.png)

What it does is prioritize the targets which are the closest to your mouse location when you attack move. So with decent mouse placement, you should be completely good to go in **team fights**.

My orbwalker is completely external by simulating clicks instead of reading and manipulating game memory. This ensures RIOT's anti-cheat to not detect the application, hence **most likely** not getting you banned. As a tradeoff, it may be a bit more challenging to work with 😉

**Comment by tranvantruong801** [comment]
RIOT's anti-cheat feature was detected and I got 2 accounts banned after just 1 game.
I tried changing the inputSimulator library again and it solved.

**Comment by diego0700** [comment]
> RIOT's anti-cheat feature was detected and I got 2 accounts banned after just 1 game. I tried changing the inputSimulator library again and it solved.
how did you do this???  I had my 3 accounts banned :(
